"""
module that provides constants for the type of errors
"""

API_PARAMETER_MISSING = "API_PARAMETER_MISSING"

PAYLOAD_MISSING_OR_EMPTY = "PAYLOAD_MISSING_OR_EMPTY"

NO_RESOURCE_FOUND = "NO_RESOURCE_FOUND"

INTERNAL_ERROR = "INTERNAL_ERROR"
