"""corrected typo with createdOn db column name in SurveyResponse

Revision ID: 3c040279a3c7
Revises: 68dbe461ad00
Create Date: 2020-01-14 23:23:18.677774

"""
# pylint: disable=no-member
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c040279a3c7'
down_revision = '68dbe461ad00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey_responses', "createdOn", new_column_name = "created_on")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey_responses', "created_on", new_column_name = "createdOn") 
    # ### end Alembic commands ###
