"""convert survey title to text

Revision ID: 68dbe461ad00
Revises: 
Create Date: 2019-12-12 17:39:14.555605

"""
# pylint: disable=no-member
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68dbe461ad00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO 
    # change server default for surveyResponse processed to false 
    op.alter_column(
        "surveys", "survey_name",
        existing_type=sa.String(length=20),
        type=sa.Text
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "surveys", "survey_name",
        existing_type=sa.Text,
        type=sa.String(length=20)
    )
    # ### end Alembic commands ###
